### PR TITLE
Safer transfer of ETH

### PR DESCRIPTION
**Pull request by asgeir-s**
I am thinking that we ignore whether the eth transfer succeeded or not so that we do not block payouts for all users. @carletex what do you think? 

My thinking: its the user's fault if they use a sketchy contract as the receiver 😝

### CODE REVIEW

**Comment by carletex** [comment]
So what happens right now? If a transfer to specific wallets fails... it will revert and no one would get the transfer?

If that's the case, I'm OK with that approach (at least for now).

We are checking that we have enough balance before sending ETH, so what could be the cause for a specific transfer to fail? Wrong address?

**Comment by asgeir-s** [comment]
> So what happens right now? If a transfer to specific wallets fails... it will revert and no one would get the transfer?
> 
> If that's the case, I'm OK with that approach (at least for now).
> 
> We are checking that we have enough balance before sending ETH, so what could be the cause for a specific transfer to fail? Wrong address?

In this branch, if one of the transfers fails, the payout will not revert. It will just continue on with the other transfers. The amount that does not get paid out will be left in the contract.

An alternative approach could be to check if the transfer is successful or not and revert if it's not successful, but in this case, all of the payouts would revert (nobody could get paid because one failed). I do not think we should use this alternative approach, as this could potentially lock the election (or require the payout of an ERC20 in order to start a new election).

A failed transfer could, for instance, happen if that the receiving address (`users[i]`) is set to some contract that executes some logic that fails (I do not think we will encounter this error).

**Comment by carletex** [comment]
Yep, that makes sense. Thank you!!

**Comment by carletex** [comment]
@sogasg I guess we are OK with this warning?

image

**Comment by asgeir-s** [comment]
> @sogasg I guess we are OK with this warning?
> 
> image

Yes 👍
It's because we do not check if the transfer succeeded or not. As so:
Screenshot 2021-09-08 at 11 40 45

**Pull request merged**
